name: Flutter CI

on:
  push:
    branches: [ addingFirebase ]
  pull_request:
    branches: [ addingFirebase ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
